### ISSUE TITLE
TXF: occasionally structopt will fail on multiple cores on a single node

### ISSUE THREAD

**Issue by cmgtam** [uw-cmg/StructOpt_modular#27]
Transferred from uw-cmg/MAST. Close if it no longer applies.

Occasionally structopt will fail on multiple cores on a single node using mpi4py.
This problem happens with approx 1% of jobs.
Min solved this problem, which apparently was that structopt was opening same potential file at the same time. The solution is to make different run directories for LAMMPS on different processors - this solution may not have been implemented for all methods.

**Comment by jjmaldonis** [comment]
@zhongnanxu I ran into this at one point too. I thought `ase.parallel.paropen` (https://wiki.fysik.dtu.dk/ase/_modules/ase/parallel.html#paropen) fixed this problem, but reading the source code I don't think it does. Min's solution may be the best solution. We should run a test using mpi4py that just opens and closes a single file (for reading, on all cores) within a for-loop and see if it breaks.

**Comment by jjmaldonis** [comment]
This ran successfully:

```
# File:  open_test.py
from mpi4py import MPI 

for i in range(1000):
    with open('ZrCu.lammps.eam') as f:
        pass
```

using `mpiexec -np 16 python open_test.py`.

**Comment by jjmaldonis** [comment]
This also ran successfully:

    import mpi4py

    for _ in range(1000):
        open("test_data.txt").readlines()

where `test_data.txt` contained 4,000 lines of `ll` print-outs

using `mpiexec -np 16 python script.py`

In addition, the current implementation of LAMMPS has been using the same potential file for every run (even though the potential file was being copied... which was therefore a bug), and we haven't had any issues after many simulations using LAMMPS.

I'm closing this issue because I'm 95% sure it's not a problem.
